"use client";

import { useContext } from "react";
import GameContext from "../context/GameContext";

const useGame = () => {
  const {
    name,
    setName,
    points,
    setPoints,
    place,
    setPlace,
    questions,
    setQuestions,
    answers,
    setAnswers,
    leaders,
    setLeaders,
    timeRemaining,
    setTimeRemaining,
    percentRemaining,
    setPercentRemaining,
    isPopped,
    isPlaying,
    setIsPopped,
    bigScreenView,
    setBigScreenView,
    startCountdown,
    setStartCountdown,
    save,
    start,
    stop,
    question,
    questionIndex,
    incorrectQuestionsCount,
    showIncorrect,
    showComponent,
    gotoNextQuestion,
    onClickAnswer,
    timeIsUp,
    clickedAnswer,
    playTransition,
    setPlayTransition,
  } = useContext(GameContext);

  return {
    name,
    setName,
    points,
    setPoints,
    place,
    setPlace,
    questions,
    setQuestions,
    answers,
    setAnswers,
    leaders,
    setLeaders,
    timeRemaining,
    setTimeRemaining,
    percentRemaining,
    setPercentRemaining,
    isPopped,
    setIsPopped,
    isPlaying,
    bigScreenView,
    setBigScreenView,
    startCountdown,
    setStartCountdown,
    save,
    start,
    stop,
    question,
    questionIndex,
    incorrectQuestionsCount,
    showIncorrect,
    showComponent,
    gotoNextQuestion,
    onClickAnswer,
    timeIsUp,
    clickedAnswer,
    playTransition,
    setPlayTransition,
  };
};

export default useGame;
